version: "2"
services:
  mysql:
     image: mysql:5.7
     restart: always
     container_name: db_piktochart
     environment:
       MYSQL_ROOT_PASSWORD: piktochart_pass
       MYSQL_DATABASE: piktochart_db
       #MYSQL_USER: piktochart_user
       #MYSQL_PASSWORD: piktochart_pass
     ports:
       - 3307:3306
  ruby:
     container_name: web_piktochart
     restart: always
     build:
      context: ./
      dockerfile: Dockerfile
     command: "bin/bundle exec rails s -p 3000 -b 0.0.0.0"
     environment:
      DATABASE_URL: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: piktochart_db
      DATABASE_USER: root
      DATABASE_PASSWORD: piktochart_pass
     ports:
      - 3000:3000
     depends_on:
      - mysql
