apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    metadata:
      name: migration
    spec:
      containers:
      - name: migration
        image: blukacs/piktochart_ruby:latest
        args: ["rake db:create && rake db:migrate"]
        env:
        - name: DATABASE_NAME
          value: "piktochart_db"
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_URL
          value: "mysql"
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "db-user-pass"
              key: "password"
        - name: RAILS_ENV
          value: "production"
      restartPolicy: Never
